// The ONE definition of "active" for a session note, plus the atomic replace.
//
// A session note is a CPT-97153 BILLING RECORD and is never destroyed. Replacing a date's note SUPERSEDES it
// (superseded_at set, retained + auditable) and creates a new active row — see migration 20260830000000.
// "Active" = superseded_at IS NULL AND deleted_at IS NULL. A note is a billing record: replacing it SUPERSEDES
// (retained) and deleting it now SOFT-DELETES (retained, recoverable) — neither destroys the row. The active
// where-clause lives in the PURE, import-free lib/activeNote.ts (so it is unit-testable) and is re-exported
// here, so every reader keeps importing it from '@/lib/sessionNotes' and the definition never drifts.
import { prisma } from '@/lib/prisma'
import { ACTIVE_NOTE_WHERE, activeNotesWhere } from './activeNote'
export { ACTIVE_NOTE_WHERE, activeNotesWhere }

export type SupersedeAndCreateInput = {
  id: string                 // pre-generated by the client → idempotent create + the superseded_by pointer
  clientId: string
  sessionDate: string
  userId: string
  noteText: string           // already filtered by the caller (both routes run the blocked-narrative backstop)
  behaviorsAddressed?: string[]
  skillsAddressed?: string[]
  interventionsUsed?: string[]
  activitiesUsed?: string[]
  generationContext?: any
  status?: string
}

// Replace a date's note ATOMICALLY: mark EVERY currently-active note for (client, date) superseded — pointing
// at the new note — and create the new active row, in one transaction. No external reader (READ COMMITTED)
// ever sees two active notes for the date, and no marker is ever orphaned. Idempotent on `id`: an autosave
// silent-retry / teardown-flush that fires this twice returns the same row instead of creating a second one
// (a deliberate replace skips the exact-dup 409 that normally provides that safety, so the explicit id is what
// prevents a duplicate). Superseding BY DATE (not a specific old id) also handles the rare multi-active-row case.
export async function supersedeAndCreate(input: SupersedeAndCreateInput): Promise<{ id: string }> {
  return prisma.$transaction(async (tx) => {
    // Deliberately NOT active-filtered: this checks whether the row we're about to create already exists (the
    // idempotency guard). It must see the row REGARDLESS of superseded_at — filtering to active here would let a
    // retry create a duplicate and break the supersede. Do not apply activeNotesWhere to this read.
    const existing = await tx.session_notes.findUnique({ where: { id: input.id }, select: { id: true } })
    if (existing) return existing // idempotent retry — same row, no dup, no re-supersede

    await tx.session_notes.updateMany({
      // Supersede only LIVE notes for the date — a deleted row stays deleted, never resurrected into a supersede.
      where: { client_id: input.clientId, session_date: input.sessionDate, superseded_at: null, deleted_at: null },
      data: { superseded_at: new Date(), superseded_by: input.id },
    })

    return tx.session_notes.create({
      data: {
        id: input.id,
        client_id: input.clientId,
        user_id: input.userId,
        note_text: input.noteText,
        session_date: input.sessionDate,
        behaviors_addressed: input.behaviorsAddressed || [],
        skills_addressed: input.skillsAddressed || [],
        interventions_used: input.interventionsUsed || [],
        activities_used: input.activitiesUsed || [],
        generation_context: input.generationContext ?? undefined,
        status: input.status || 'saved',
      },
      select: { id: true },
    })
  })
}
